steps:
  - group: ":snyk: Snyk Scans"
    key: "snyk"
    steps:
    - label: ":snyk: OSS Scan"
      plugins:
      - snyk#v0.1.0:
          scan: 'oss'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          annotate: false
         

    - label: ":snyk: Code scan"
      plugins:
      - snyk#v0.1.0:
          scan: 'code'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          annotate: true
      
    - label: ":snyk: Container Scan"
      plugins:
      - snyk#v0.1.0:
          scan: 'container'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          image: snyk/snyk-container-demo
          annotate: true
