steps:
  - group: ":snyk: Snyk Code and OSS Scans"
    key: "snyk"
    steps:
    - label: ":snyk: OSS Scan"
      plugins:
      - snyk#v0.1.0:
          scan: 'oss'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          annotate: true

    - label: ":snyk: Code scan"
      plugins:
      - snyk#v0.1.0:
          scan: 'code'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          annotate: true

  - wait
  
  - label: ":hammer_and_wrench: Building a container image"
    command: "echo Building container"
    key: "build_container"
  
  - label: ":snyk: Container Scan"
    depends_on: "build_container"
    plugins:
    - snyk#v0.1.0:
        scan: 'container'
        token-env: 'BUILDKITE_SNYK_TOKEN'
        image: snyk/snyk-container-demo
        annotate: true
        block: true

  - wait
  
  - label: ":rspec: Run tests"
    command: "echo Running tests"
    key: "tests"

  - label: ":octopus-deploy: Deploy"
    command: "echo Deploying"
    depends_on: "tests"
